name: Bandit

on:
  push:
    branches: [main]  # Only trigger on push to the main branch
  pull_request:
    branches: [main]  # Only trigger on pull requests to the main branch
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exit_zero: true  # Set to true to prevent failure on finding issues
          level: HIGH  # Optional: Report only high severity issues
          confidence: HIGH  # Optional: Report only high confidence issues
          excluded_paths: ".tox,.git,__pycache__"  # Optional: Exclude directories you don't need scanned
          skips: "B301,B302"  # Optional: Skip specific tests, replace with IDs of tests to skip
