name: Bandit Code Scan

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r .
