# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Bandit is a security linter designed to find common security issues in Python code.
# This action will run Bandit on your codebase.
# The results of the scan will be found under the Security tab of your repository.

# https://github.com/marketplace/actions/bandit-scan is ISC licensed, by abirismyname
# https://pypi.org/project/bandit/ is Apache v2.0 licensed, by PyCQA

name: Bandit Security Scan

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to 'main'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday (UTC)

jobs:
  bandit:
    runs-on: ubuntu-latest  # The environment to run the workflow
    permissions:
      contents: read  # Required for GitHub Actions to access the repository code
      security-events: write  # Allow Bandit to create security events in the repository
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit  # Install Bandit

      - name: Run Bandit Security Linter
        run: |
          bandit -r . -f json -o bandit_report.json  # Run Bandit recursively from the current directory and generate a report
          
      - name: Upload Bandit Report as Artifact
        uses: acti
